global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service:8000"]
    metrics_path: /users/metrics
    scrape_interval: 10s