FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .
COPY auth_service/alembic.ini .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "task_service.app.main:app", "--host", "0.0.0.0", "--port", "8000"]